// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbf_nxpIYTGrwnwih_aEIwW2hdYZHCa8Y',
    appId: '1:726541233100:web:d39a702e677df89989cb69',
    messagingSenderId: '726541233100',
    projectId: 'profil-b7410',
    authDomain: 'profil-b7410.firebaseapp.com',
    storageBucket: 'profil-b7410.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxcQLhFEUqZB3SfkBdDLCaR9RqcJzv8D0',
    appId: '1:726541233100:android:62272d15d307ff8789cb69',
    messagingSenderId: '726541233100',
    projectId: 'profil-b7410',
    storageBucket: 'profil-b7410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejXfR2l0A2VjS4DO8i1yba65hfQ5iclE',
    appId: '1:726541233100:ios:2544d2f6cd9ccbe489cb69',
    messagingSenderId: '726541233100',
    projectId: 'profil-b7410',
    storageBucket: 'profil-b7410.appspot.com',
    iosClientId: '726541233100-lrravorhjmo4g2bmc69bctkuaksddsm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejXfR2l0A2VjS4DO8i1yba65hfQ5iclE',
    appId: '1:726541233100:ios:2544d2f6cd9ccbe489cb69',
    messagingSenderId: '726541233100',
    projectId: 'profil-b7410',
    storageBucket: 'profil-b7410.appspot.com',
    iosClientId: '726541233100-lrravorhjmo4g2bmc69bctkuaksddsm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
